import "./style-2010.css";
import wla from "../../../assets/2010-Women-In-Leadership.jpg";

const Event2 = () => {
  return (
    <div className="event-container panel-maroon">
      <div className="col-2">
        <div>
          <h1 className="year white-txt">2010</h1>
          <h2>Challenger</h2>
          <p>
            In 2010, students at CMC approached Sarah Smith Orr (then Executive
            Director of the Kravis Leadership Institute at CMC) about the need
            and desire for female leadership mentors on campus. Support quickly
            came together for the first Women & Leadership Workshop, designed to
            support all 7-C students during their time of preparation for
            post-graduation opportunities and employment, as well as connecting
            students with successful women leaders representing fields such as
            law, non-profit, entrepreneurship, finance, consulting,
            entertainment, education, government service, marketing, and health
            services. We decided to capitalize on the momentum generated by the
            workshop’s success, and thus, the Women & Leadership Alliance was
            born."
          </p>
        </div>
      </div>
      <div className="col-4">
        <img
          className="fullwidth"
          src={wla}
          alt="The inaugural Women In Leadership Alliance event."
        />
      </div>
    </div>
  );
};

export default Event2;
